export const GET_ALL_USER_BY_TYPE_LOAD  = "GET_ALL_USER_BY_TYPE_LOAD";
export const GET_ALL_USER_BY_TYPE_SUCCESS  = "GET_ALL_USER_BY_TYPE_SUCCESS";
export const GET_ALL_USER_BY_TYPE_FAIL  = "GET_ALL_USER_BY_TYPE_FAIL";
